<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <PackageId>Palisades</PackageId>
    <Version>1.2.0</Version>
    <Authors>Xavier Stouder</Authors>
    <Company>StouderIO</Company>
    <Product>Palisades</Product>
    <RepositoryUrl>https://github.com/Xstoudi/Palisades</RepositoryUrl>
    <AssemblyName>Palisades</AssemblyName>
    <ApplicationIcon>Ressources\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="gong-wpf-dragdrop" Version="3.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.122" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Ressources\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Localization\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <Page Remove="Themes\**\*.xaml" />
    <None Include="Themes\**\*.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
